config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }
  root to: 'welcome#index'
  resources :goals
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :user_name, presence: true, length: { minimum: 4, maximum: 25 }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :goals
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :set_goal, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :owned_goal, only: [:edit, :update, :destroy]

  def index
    @goals = Goal.all.order('created_at DESC')
  end

  def new
    @goal = current_user.goals.build
  end

  def create
    @goal = current_user.goals.build(goal_params)
    if @goal.save
      flash[:success] = 'Your goals were saved'
      redirect_to goal_path(@goal)
    else
      flash[:alert] = 'Your goals were not saved. Please try again.'
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @goal.update(goal_params)
      flash[:success] = 'Goals Updated.'
      redirect_to goal_path(@goal)
    else
      flash[:alert] = 'Something went wrong. Please try again.'
      render :edit
    end
  end

  def destroy
    @goal.destroy
    flash[:success] = 'Your goal has been deleted.'
    redirect_to goals_path
  end


  private

  def goal_params
    params.require(:goal).permit(:year, :month, :goal1, :goal2, :goal3)
  end

  def set_goal
    @goal = Goal.find(params[:id])
  end

  def owned_goal
    unless current_user == @goal.user
      flash[:alert] = "This goal doesn't belong to you"
      redirect_to root_path
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :current_password)
  end
end 

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/goals/edit.html.erb
<h2>Are you really sure you want to edit your planner?</h2>
  <%= simple_form_for @goal do |f| %>
  <%= f.error_notification %>
  <div class="panel-body">
    <%= f.input :year, priority: [ "2016" ], collection: [ "2016", "2017", "2018", "2019", "2020", "2021", "2022"], required: true, label: false %>
    <%= f.input :month, priority: [ "October" ], collection: [ "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"], required: true, label: false %>
    <%= f.input :goal1, required: true, label: false, placeholder: 'A must do for the month', input_html: { class: 'input-lg' } %>
    <%= f.input :goal2, required: true, label: false, placeholder: 'A should do for the month', input_html: { class: 'input-lg' } %>
    <%= f.input :goal3, required: true, label: false, placeholder: 'Something that would make you happy if you could do', input_html: { class: 'input-lg' } %>
    <%= f.button :submit, "Save Goals", class: 'btn-lg btn-info btn-block' %>
  </div>
<% end %>

<div class="text-center edit-links">
  <%= link_to "Delete Goals", goal_path(@goal), method: :delete, data: { confirm: "Are you sure you want to delete this goal?" } %>
  |
  <%= link_to "Cancel", goals_path %>
</div>

app/views/goals/index.html.erb
<%= link_to '--> Add a New Monthly Planner', new_goal_path %>
<p>
My Previous Goals:
</p>
<% @goals.each do |goal| %>
  <p><%= link_to goal.month + ' ' + goal.year, goal_path(goal) %></p>
<% end %>

app/views/goals/new.html.erb
<h2>Monthly Planner Generator</h2>
  <%= simple_form_for @goal do |f| %>
  <%= f.error_notification %>
  <div class="panel-body">
    <%= f.input :year, priority: [ "2016" ], collection: [ "2016", "2017", "2018", "2019", "2020", "2021", "2022"], required: true, label: false %>
    <%= f.input :month, priority: [ "October" ], collection: [ "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"], required: true, label: false %>
    <%= f.input :goal1, required: true, label: false, placeholder: 'A must do for the month', input_html: { class: 'input-lg' } %>
    <%= f.input :goal2, required: true, label: false, placeholder: 'A should do for the month', input_html: { class: 'input-lg' } %>
    <%= f.input :goal3, required: true, label: false, placeholder: 'Something that would make you happy if you could do', input_html: { class: 'input-lg' } %>
    <%= f.button :submit, "Save Goals", class: 'btn-lg btn-info btn-block' %>
  </div>
<% end %>

app/views/goals/show.html.erb
<%= @goal.year %>
<%= @goal.month %>
<%= @goal.goal1 %>
<%= @goal.goal2 %>
<%= @goal.goal3 %>

<% if @goal.user.id == current_user.id %>
  <div class="text-center edit-links">
    <%= link_to "Cancel", goals_path %>
    |
    <%= link_to "Edit Goals", edit_goal_path(@goal) %>
  </div>
<% else %>
  <div class="text-center edit-links">
    <%= link_to "Cancel", goals_path %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid navbar-container">
    <div class="navbar-header">
      <button class="navbar-toggle collapsed" data-target="#bs-navbar-collapse-1" data-toggle="collapse" type="button">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand">
        <%= link_to "Month by Month", root_path %>
      </div>
    </div>
    <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "To Do's", goals_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Register", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photogram</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Month by Month</h1>
<h3>Welcome to Month by Month, where you can set and achieve your monthly goals.</h3>

<li>
  <ul><h5>Set a maximum of 3 goals each month. No edit.</h5></ul>
</li>
<li>
  <ul><h5>Make your goals measurable and achievable.</h5></ul>
</li>
<li>
  <ul><h5>Print your goals and put it on your wall, and also put it as your background image in both your laptop and mobile.</h5></ul>
</li>
<li>
  <ul><h5>Use the comments to add info or comments regarding each month golas.</h5></ul>
</li>
<li>
  <ul><h5>Share your monthly goals with your friends and family. Put it out there and commit to it.</h5></ul>
</li>

<% if user_signed_in? %>
  <h4>Have you define this month's goals? <%= link_to "To Do's", goals_path %></h4>
<% else %>
  <h4><%= link_to "Login", new_user_session_path %> / <%= link_to "Register", new_user_registration_path %> and start defining your goals.</h4>
<% end %>